spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: huangxu123
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.tssf.blog.* #监控springBean
      filters: stat,wall #底层开启监控功能 防火墙功能
      stat-view-servlet: #配置监控登录页功能
        enabled: true
        login-username: root
        login-password: 123456
        reset-enable: false

      web-stat-filter: #监控web应用
        enabled: true
        url-pattern: /*

      filter:
        stat:      #对上面filters里面stat的详细配置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
server:
  port: 8888

